[package]
name = "waitfree-sync"
version = "0.3.3"
edition = "2021"
rust-version = "1.81"
license = "MIT OR Apache-2.0"
repository = "https://github.com/novomation/waitfree-sync"
homepage = "https://github.com/novomation/waitfree-sync"
authors = ["Marc Fischer"]
readme = "Readme.md"
exclude = [".github/*"]
description = "A collection of wait-free data structures"
keywords = ["wait-free", "queue", "buffer", "non-blocking", "lock-free"]
categories = ["concurrency", "memory-management", "data-structures"]

[dependencies]
crossbeam-utils = "0.8"
libc = { version = "0.2", optional = true }
tokio = { version = "1.53", features = ["net", "rt"], optional = true }


[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
core_affinity = "0.8"
tokio = { version = "1.53", features = [
    "net",
    "rt",
    "rt-multi-thread",
    "sync",
] }

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[features]
default = ["async"]
async = ["dep:libc", "dep:tokio"]

[[bench]]
name = "spsc"
harness = false


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
